### PR TITLE
Return defensive copies of TSet from the HQDM methods.

### PR DESCRIPTION
**Pull request by twalmsley**
I did this in two places rather than just doing it in `getRelated()` since in some cases the TSet isn't returned outside the HQDM class so the clone would serve no purpose.

### CODE REVIEW

**Comment by amrc-benmorrow** [comment]
Is `getRelated` public API? The intention of my PR was that it should be (and so should `relate` and `related`), unless you have a strong objection. In which case the public `getRelated` also needs to return a clone, but maybe we want a private `_getRelated` which doesn't for internal use.

**Comment by twalmsley** [comment]
Good spot, I missed that. Originally I was going to put it in `getRelated()` but then saw the internal uses that don't need a clone. I can move cloning into `getRelated()` and add a private `_getRelated()`.

On a private project I have an immutable version of TSet where the `add` method returns a new TSet, and I have an internal `privateAdd` which makes sure entries aren't duplicated. We'll end up with more copying of the internal array unless we switch to using lists internally where we add entries only at the head. This means the tail is immutable and can be shared between copies of the TSet and we won't need a clone(), but will mean we need a new implementation of Lists, which can be inefficient to traverse.

What do you think?

**Comment by twalmsley** [comment]
I would tend to agree - immutability is great but we're short on time. There are some other methods that also return Arrays so I'll update them all to return Iterables, which might be a breaking change but worth doing.

**Comment by twalmsley** [comment]
So, returning Iterables means that consumers can't easily cal methods like `map()`, `size()`, `has()` etc. that TSet provides - your only option is to iterate. So on balance I'd prefer to return a TSet.clone() instead. We're still able to change the underlying implementation to something other than an Array, and I can also make TSet return the underlying Iterator for the Array for people who prefer `for` loops over `map`, `filter` etc.
Is that ok?

**Comment by amrc-benmorrow** [comment]
Yes, sounds reasonable to me at this point. If it's straightforward it would be good to implement Symbol.iterator on TSet so that people can use it as a generic iterator if they want to.

**Comment by twalmsley** [comment]
Ok that's done, and there's a test to show that TSet is now Iterable as well.

**Review by amrc-benmorrow — APPROVED** [review]

**Pull request merged**
